//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EyEServer.Resources.Localization.Identity; 
using System;


/// <summary>
///   A strongly-typed resource class, for looking up localized strings, etc.
/// </summary>
// This class was auto-generated by the StronglyTypedResourceBuilder
// class via a tool like ResGen or Visual Studio.
// To add or remove a member, edit your .ResX file then rerun ResGen
// with the /str option, or rebuild your VS project.
[global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
internal class IdentityResource {
    
    private static global::System.Resources.ResourceManager resourceMan;
    
    private static global::System.Globalization.CultureInfo resourceCulture;
    
    [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
    internal IdentityResource() {
    }
    
    /// <summary>
    ///   Returns the cached ResourceManager instance used by this class.
    /// </summary>
    [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
    internal static global::System.Resources.ResourceManager ResourceManager {
        get {
            if (object.ReferenceEquals(resourceMan, null)) {
                global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EyEServer.Resources.Localization.Identity.IdentityResource", typeof(IdentityResource).Assembly);
                resourceMan = temp;
            }
            return resourceMan;
        }
    }
    
    /// <summary>
    ///   Overrides the current thread's CurrentUICulture property for all
    ///   resource lookups using this strongly typed resource class.
    /// </summary>
    [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
    internal static global::System.Globalization.CultureInfo Culture {
        get {
            return resourceCulture;
        }
        set {
            resourceCulture = value;
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to The password reset code was sent by email.
    /// </summary>
    internal static string CodeSentToEmail {
        get {
            return ResourceManager.GetString("CodeSentToEmail", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Email confirm  token empty.
    /// </summary>
    internal static string EmailConfirmationTokenEmpty {
        get {
            return ResourceManager.GetString("EmailConfirmationTokenEmpty", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Your email is not verified.
    /// </summary>
    internal static string EmailNotConfirmed {
        get {
            return ResourceManager.GetString("EmailNotConfirmed", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Invalid password reset code.
    /// </summary>
    internal static string InvalidPasswordResetCode {
        get {
            return ResourceManager.GetString("InvalidPasswordResetCode", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Nickname&quot;{0}&quot; is taken.
    /// </summary>
    internal static string NicknameExists {
        get {
            return ResourceManager.GetString("NicknameExists", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Password reset code: {0}.
    /// </summary>
    internal static string PasswordResetMessage {
        get {
            return ResourceManager.GetString("PasswordResetMessage", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Password reset.
    /// </summary>
    internal static string PasswordResetMessageHeader {
        get {
            return ResourceManager.GetString("PasswordResetMessageHeader", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Email confirmation.
    /// </summary>
    internal static string RegisterConfirmHeader {
        get {
            return ResourceManager.GetString("RegisterConfirmHeader", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Confirm your registration by following the link: &lt;a href={0}&gt;link&lt;/a&gt;.
    /// </summary>
    internal static string RegisterConfirmMessage {
        get {
            return ResourceManager.GetString("RegisterConfirmMessage", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to To complete registration, check your email and follow the link provided in the letter, then you will be able to log in. For your convenience, the data has already been inserted..
    /// </summary>
    internal static string RegistrationCompletionMessage {
        get {
            return ResourceManager.GetString("RegistrationCompletionMessage", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Administration of site.
    /// </summary>
    internal static string SiteAdministration {
        get {
            return ResourceManager.GetString("SiteAdministration", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Thanks for the&lt;br/&gt;
    ///confirmation&lt;br/&gt;
    ///email..
    /// </summary>
    internal static string ThanksConfirmationEmail {
        get {
            return ResourceManager.GetString("ThanksConfirmationEmail", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to User &quot;{0}&quot; already exists. Try login..
    /// </summary>
    internal static string UserExists {
        get {
            return ResourceManager.GetString("UserExists", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to User &quot;{0}&quot; does not exist.
    /// </summary>
    internal static string UserNotExists {
        get {
            return ResourceManager.GetString("UserNotExists", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Incorrect login or password.
    /// </summary>
    internal static string WrongLoginOrPassword {
        get {
            return ResourceManager.GetString("WrongLoginOrPassword", resourceCulture);
        }
    }
}
