//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EyEClientLib.Resources.Localization.Identity; 
using System;


/// <summary>
///   A strongly-typed resource class, for looking up localized strings, etc.
/// </summary>
// This class was auto-generated by the StronglyTypedResourceBuilder
// class via a tool like ResGen or Visual Studio.
// To add or remove a member, edit your .ResX file then rerun ResGen
// with the /str option, or rebuild your VS project.
[global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
internal class IdentityResource {
    
    private static global::System.Resources.ResourceManager resourceMan;
    
    private static global::System.Globalization.CultureInfo resourceCulture;
    
    [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
    internal IdentityResource() {
    }
    
    /// <summary>
    ///   Returns the cached ResourceManager instance used by this class.
    /// </summary>
    [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
    internal static global::System.Resources.ResourceManager ResourceManager {
        get {
            if (object.ReferenceEquals(resourceMan, null)) {
                global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EyEClientLib.Resources.Localization.Identity.IdentityResource", typeof(IdentityResource).Assembly);
                resourceMan = temp;
            }
            return resourceMan;
        }
    }
    
    /// <summary>
    ///   Overrides the current thread's CurrentUICulture property for all
    ///   resource lookups using this strongly typed resource class.
    /// </summary>
    [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
    internal static global::System.Globalization.CultureInfo Culture {
        get {
            return resourceCulture;
        }
        set {
            resourceCulture = value;
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Authorization.
    /// </summary>
    internal static string Authorization {
        get {
            return ResourceManager.GetString("Authorization", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Change password.
    /// </summary>
    internal static string ChangePassword {
        get {
            return ResourceManager.GetString("ChangePassword", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to A code has been sent to your email.
    /// </summary>
    internal static string CodeSentToEmail {
        get {
            return ResourceManager.GetString("CodeSentToEmail", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Email.
    /// </summary>
    internal static string Email {
        get {
            return ResourceManager.GetString("Email", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Exit.
    /// </summary>
    internal static string Exit {
        get {
            return ResourceManager.GetString("Exit", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to I forgot my password.
    /// </summary>
    internal static string ForgotPassword {
        get {
            return ResourceManager.GetString("ForgotPassword", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Get code.
    /// </summary>
    internal static string GetCode {
        get {
            return ResourceManager.GetString("GetCode", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Login.
    /// </summary>
    internal static string Login {
        get {
            return ResourceManager.GetString("Login", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to We are all fed up with password restrictions, there are none here, like in other applications, it can even be empty, all at your own peril and risk :).
    /// </summary>
    internal static string NoRestrictionsForPassword {
        get {
            return ResourceManager.GetString("NoRestrictionsForPassword", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Password.
    /// </summary>
    internal static string Password {
        get {
            return ResourceManager.GetString("Password", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Open the password change window.
    /// </summary>
    internal static string PasswordChangeWindow {
        get {
            return ResourceManager.GetString("PasswordChangeWindow", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Enter code.
    /// </summary>
    internal static string PlaceholderCode {
        get {
            return ResourceManager.GetString("PlaceholderCode", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Enter e-mail.
    /// </summary>
    internal static string PlaceholderEmail {
        get {
            return ResourceManager.GetString("PlaceholderEmail", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Nickname (\/)_(0_o)_(\/).
    /// </summary>
    internal static string PlaceholderNickname {
        get {
            return ResourceManager.GetString("PlaceholderNickname", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Enter password.
    /// </summary>
    internal static string PlaceholderPassword {
        get {
            return ResourceManager.GetString("PlaceholderPassword", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Repeat password.
    /// </summary>
    internal static string PlaceholderRepeatPassword {
        get {
            return ResourceManager.GetString("PlaceholderRepeatPassword", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Register.
    /// </summary>
    internal static string Register {
        get {
            return ResourceManager.GetString("Register", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Registration.
    /// </summary>
    internal static string Registration {
        get {
            return ResourceManager.GetString("Registration", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to &quot;I have read and accept &lt;a&gt;registration conditions&lt;/a&gt;&quot;.
    /// </summary>
    internal static string RegistrationConditionsCheckBox {
        get {
            return ResourceManager.GetString("RegistrationConditionsCheckBox", resourceCulture);
        }
    }
}
