//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Identity.Resources.Localization; 
using System;


/// <summary>
///   A strongly-typed resource class, for looking up localized strings, etc.
/// </summary>
// This class was auto-generated by the StronglyTypedResourceBuilder
// class via a tool like ResGen or Visual Studio.
// To add or remove a member, edit your .ResX file then rerun ResGen
// with the /str option, or rebuild your VS project.
[global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
internal class IdentityResource {
    
    private static global::System.Resources.ResourceManager resourceMan;
    
    private static global::System.Globalization.CultureInfo resourceCulture;
    
    [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
    internal IdentityResource() {
    }
    
    /// <summary>
    ///   Returns the cached ResourceManager instance used by this class.
    /// </summary>
    [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
    internal static global::System.Resources.ResourceManager ResourceManager {
        get {
            if (object.ReferenceEquals(resourceMan, null)) {
                global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Identity.Resources.Localization.IdentityResource", typeof(IdentityResource).Assembly);
                resourceMan = temp;
            }
            return resourceMan;
        }
    }
    
    /// <summary>
    ///   Overrides the current thread's CurrentUICulture property for all
    ///   resource lookups using this strongly typed resource class.
    /// </summary>
    [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
    internal static global::System.Globalization.CultureInfo Culture {
        get {
            return resourceCulture;
        }
        set {
            resourceCulture = value;
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Поле &quot;Код подтвержения&quot; не заполнено.
    /// </summary>
    internal static string CodeRequired {
        get {
            return ResourceManager.GetString("CodeRequired", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Поле &quot;E-mail&quot; некорректно.
    /// </summary>
    internal static string EmailIncorrect {
        get {
            return ResourceManager.GetString("EmailIncorrect", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Поле &quot;E-mail&quot; не заполнено.
    /// </summary>
    internal static string EmailRequired {
        get {
            return ResourceManager.GetString("EmailRequired", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Поле &quot;Потверждение Пароля&quot; не заполнено.
    /// </summary>
    internal static string PasswordConfirmRequired {
        get {
            return ResourceManager.GetString("PasswordConfirmRequired", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Пароль должен содержать {2}-{1} символов.
    /// </summary>
    internal static string PasswordLength {
        get {
            return ResourceManager.GetString("PasswordLength", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Пароль должен содержать миниум одну: 
    ///1) прописную букву
    ///2) срочную букву
    ///3) цифру.
    /// </summary>
    internal static string PasswordOneUppercaseAndOneLowercaseAndOneNumeric {
        get {
            return ResourceManager.GetString("PasswordOneUppercaseAndOneLowercaseAndOneNumeric", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Поле &quot;Пароль&quot; не заполнено.
    /// </summary>
    internal static string PasswordRequired {
        get {
            return ResourceManager.GetString("PasswordRequired", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Пароли не совпадают.
    /// </summary>
    internal static string PasswordsNotMatch {
        get {
            return ResourceManager.GetString("PasswordsNotMatch", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Условия регистрации не приняты.
    /// </summary>
    internal static string RegistrationConditions {
        get {
            return ResourceManager.GetString("RegistrationConditions", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Поддерживаемые домены почт.
    /// </summary>
    internal static string SupportedMailDomains {
        get {
            return ResourceManager.GetString("SupportedMailDomains", resourceCulture);
        }
    }
}
